services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: amrutam_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: amrutam_user
      POSTGRES_PASSWORD: amrutam_pass
      POSTGRES_DB: amrutam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: amrutam_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: amrutam_jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "4318:4318"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: amrutam_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: 15m
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      OTEL_EXPORTER_URL: http://jaeger:4318/v1/traces
      NODE_ENV: production
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRY: 7d
      GROQ_API_KEY: ${GROQ_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    volumes:
      - ./backend/uploads:/app/uploads   # NEW — yahan aana chahiye tha, service ke andar
    depends_on:
      - postgres
      - redis
      - jaeger

volumes:
  pgdata: